# Generated by Django 5.2 on 2025-05-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=100)),
                ('spanish', models.CharField(blank=True, max_length=100, null=True)),
                ('french', models.CharField(blank=True, max_length=100, null=True)),
                ('russian', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category_name', models.CharField(max_length=50)),
                ('category_level', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Word',
                'verbose_name_plural': 'Words',
                'ordering': ['-created_at'],
            },
        ),
    ]
