# Generated by Django 5.2 on 2025-05-31 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrenchWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun_form', models.CharField(blank=True, max_length=100, null=True)),
                ('verb_form', models.CharField(blank=True, max_length=100, null=True)),
                ('adjective_form', models.CharField(blank=True, max_length=100, null=True)),
                ('adverb_form', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'French Word',
                'verbose_name_plural': 'French Words',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FrenchExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('french_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='words.frenchword')),
            ],
            options={
                'verbose_name': 'French Example',
                'verbose_name_plural': 'French Examples',
                'ordering': ['french_word', 'id'],
            },
        ),
    ]
