# Generated by Django 5.2 on 2025-05-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_frenchword_frenchexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='frenchword',
            name='original_phrase',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
