# Generated by Django 5.2 on 2025-06-07 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_frenchword_original_phrase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frenchword',
            name='adjective_form',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='frenchword',
            name='adverb_form',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='frenchword',
            name='noun_form',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='frenchword',
            name='verb_form',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
