# Generated by Django 5.2 on 2025-06-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0004_alter_frenchword_adjective_form_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='frenchword',
            constraint=models.UniqueConstraint(condition=models.Q(('noun_form__isnull', False)), fields=('noun_form',), name='unique_noun_form'),
        ),
        migrations.AddConstraint(
            model_name='frenchword',
            constraint=models.UniqueConstraint(condition=models.Q(('verb_form__isnull', False)), fields=('verb_form',), name='unique_verb_form'),
        ),
        migrations.AddConstraint(
            model_name='frenchword',
            constraint=models.UniqueConstraint(condition=models.Q(('adjective_form__isnull', False)), fields=('adjective_form',), name='unique_adjective_form'),
        ),
        migrations.AddConstraint(
            model_name='frenchword',
            constraint=models.UniqueConstraint(condition=models.Q(('adverb_form__isnull', False)), fields=('adverb_form',), name='unique_adverb_form'),
        ),
    ]
