# Generated by Django 5.2 on 2025-06-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_frenchword_unique_noun_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frenchword',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='marked_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
