# Generated by Django 5.2 on 2025-06-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_frenchword_category_frenchword_frequency_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frenchexample',
            options={'ordering': ['-is_explanation', 'id'], 'verbose_name': 'French Example', 'verbose_name_plural': 'French Examples'},
        ),
        migrations.AddField(
            model_name='frenchexample',
            name='is_explanation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='antonym_adjective_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='antonym_adverb_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='antonym_noun_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='antonym_verb_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='synonym_adjective_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='synonym_adverb_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='synonym_noun_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='synonym_verb_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
