# Generated by Django 5.2 on 2025-06-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_alter_frenchexample_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frenchword',
            name='category_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
