# Generated by Django 5.2 on 2025-06-12 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_airesponse_frenchword_ai_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frenchword',
            name='ai_response',
        ),
        migrations.DeleteModel(
            name='AIResponse',
        ),
    ]
