# Generated by Django 5.2 on 2025-06-14 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_remove_frenchword_ai_response_delete_airesponse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frenchword',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='frenchword',
            name='unique_noun_form',
        ),
        migrations.RemoveConstraint(
            model_name='frenchword',
            name='unique_verb_form',
        ),
        migrations.RemoveConstraint(
            model_name='frenchword',
            name='unique_adjective_form',
        ),
        migrations.RemoveConstraint(
            model_name='frenchword',
            name='unique_adverb_form',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='adjective_form',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='adverb_form',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='antonym_adjective_form',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='antonym_adverb_form',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='antonym_noun_form',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='antonym_verb_form',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='category',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='category_2',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='noun_form',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='original_phrase',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='synonym_adjective_form',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='synonym_adverb_form',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='synonym_noun_form',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='synonym_verb_form',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='verb_form',
        ),
        migrations.AddField(
            model_name='frenchword',
            name='antonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='definition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='examples',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='language',
            field=models.CharField(default='french', max_length=50),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='synonyms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='word',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='frenchexample',
            name='french_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_examples', to='words.frenchword'),
        ),
    ]
