# Generated by Django 5.2 on 2025-06-14 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0011_alter_frenchword_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frenchword',
            options={'ordering': ['id'], 'verbose_name': 'French Word', 'verbose_name_plural': 'French Words'},
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='antonyms',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='examples',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='language',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='synonyms',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='frenchword',
            name='word',
        ),
        migrations.AddField(
            model_name='frenchword',
            name='adjective_form',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='adverb_form',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='antonym_adjective_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='antonym_adverb_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='antonym_noun_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='antonym_verb_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='category_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='frequency',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='noun_form',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='original_phrase',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='synonym_adjective_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='synonym_adverb_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='synonym_noun_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='synonym_verb_form',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='frenchword',
            name='verb_form',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='frenchexample',
            name='french_word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='words.frenchword'),
        ),
        migrations.AddConstraint(
            model_name='frenchword',
            constraint=models.UniqueConstraint(condition=models.Q(('noun_form__isnull', False)), fields=('noun_form',), name='unique_noun_form'),
        ),
        migrations.AddConstraint(
            model_name='frenchword',
            constraint=models.UniqueConstraint(condition=models.Q(('verb_form__isnull', False)), fields=('verb_form',), name='unique_verb_form'),
        ),
        migrations.AddConstraint(
            model_name='frenchword',
            constraint=models.UniqueConstraint(condition=models.Q(('adjective_form__isnull', False)), fields=('adjective_form',), name='unique_adjective_form'),
        ),
        migrations.AddConstraint(
            model_name='frenchword',
            constraint=models.UniqueConstraint(condition=models.Q(('adverb_form__isnull', False)), fields=('adverb_form',), name='unique_adverb_form'),
        ),
    ]
