# Generated by Django 5.2 on 2025-08-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0013_spanishword_spanishexample'),
    ]

    operations = [
        migrations.AddField(
            model_name='frenchword',
            name='native',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spanishword',
            name='native',
            field=models.BooleanField(default=True),
        ),
    ]
