# Generated by Django 5.2 on 2025-08-09 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0016_russianword_russianexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='JapaneseWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun_form', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('verb_form', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('adjective_form', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('adverb_form', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('synonym_noun_form', models.CharField(blank=True, max_length=100, null=True)),
                ('synonym_verb_form', models.CharField(blank=True, max_length=100, null=True)),
                ('synonym_adjective_form', models.CharField(blank=True, max_length=100, null=True)),
                ('synonym_adverb_form', models.CharField(blank=True, max_length=100, null=True)),
                ('antonym_noun_form', models.CharField(blank=True, max_length=100, null=True)),
                ('antonym_verb_form', models.CharField(blank=True, max_length=100, null=True)),
                ('antonym_adjective_form', models.CharField(blank=True, max_length=100, null=True)),
                ('antonym_adverb_form', models.CharField(blank=True, max_length=100, null=True)),
                ('original_phrase', models.CharField(blank=True, max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marked_for_review', models.BooleanField(default=False)),
                ('frequency', models.CharField(blank=True, max_length=50, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('category_2', models.CharField(blank=True, max_length=100, null=True)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('native', models.BooleanField(default=True)),
                ('kanji_form', models.CharField(blank=True, max_length=200, null=True)),
                ('kana_reading', models.CharField(blank=True, max_length=200, null=True)),
                ('romaji', models.CharField(blank=True, max_length=200, null=True)),
                ('furigana', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Japanese Word',
                'verbose_name_plural': 'Japanese Words',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('noun_form__isnull', False)), fields=('noun_form',), name='unique_japanese_noun_form'), models.UniqueConstraint(condition=models.Q(('verb_form__isnull', False)), fields=('verb_form',), name='unique_japanese_verb_form'), models.UniqueConstraint(condition=models.Q(('adjective_form__isnull', False)), fields=('adjective_form',), name='unique_japanese_adjective_form'), models.UniqueConstraint(condition=models.Q(('adverb_form__isnull', False)), fields=('adverb_form',), name='unique_japanese_adverb_form')],
            },
        ),
        migrations.CreateModel(
            name='JapaneseExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('example_text', models.TextField()),
                ('is_explanation', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('japanese_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examples', to='words.japaneseword')),
            ],
            options={
                'verbose_name': 'Japanese Example',
                'verbose_name_plural': 'Japanese Examples',
                'ordering': ['-is_explanation', 'id'],
            },
        ),
    ]
