# Generated by Django 5.2 on 2025-08-09 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0017_japaneseword_japaneseexample'),
    ]

    operations = [
        migrations.CreateModel(
            name='LexemeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MigrationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_language', models.CharField(max_length=8)),
                ('target_languages', models.JSONField(default=list)),
                ('status', models.CharField(default='created', max_length=32)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LexemeGroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=8)),
                ('word_id', models.PositiveBigIntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='words.lexemegroup')),
            ],
            options={
                'indexes': [models.Index(fields=['group', 'language'], name='words_lexem_group_i_d28e74_idx')],
                'unique_together': {('language', 'word_id')},
            },
        ),
        migrations.CreateModel(
            name='MigrationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_language', models.CharField(max_length=8)),
                ('source_word_id', models.PositiveBigIntegerField()),
                ('target_language', models.CharField(max_length=8)),
                ('status', models.CharField(default='pending', max_length=32)),
                ('target_word_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='words.migrationbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['batch', 'source_language', 'source_word_id', 'target_language'], name='words_migra_batch_i_ebbc39_idx')],
                'unique_together': {('batch', 'source_language', 'source_word_id', 'target_language')},
            },
        ),
    ]
